version: 0.1.1
env:
  - SLACK_QUANTUM_BUILD_CHANNEL : "#dynamo-jenkinsbuild"
  - SLACK_QUANTUM_BUILD_CREDENTIAL_ID : "slack-notify-token"
  - MAIL_QUANTUM_BUILD_RECIPIENT : "dynamo.plaid.dev@autodesk.com"
  - ARTIFACTORY_BOBCAT_DOCKER_REGISTRY : "artifactory.dev.adskengineer.net"
  - NUGET_API_ID : "dynamovisualprogramming_nuget_api_key"
  - ARTIFACTORY_DOCKER_CREDENTIALS_ID : "common_service_account"

check_changelog_updated_on_pr: false
pipeline_os: "Linux"
force_slack_notification : true
nodejs_version: "10"

jenkins_creds:
  -
    type: secretText
    credentialsId: dynamovisualprogramming_nuget_api_key
    secretText: API_KEY

build:
  -
    customized_builder_image:
      registry: artifactory
      url: artifactory.dev.adskengineer.net/docker-local-v2/dynamo/dynamolibrariejs:dotnetcore2
    scripts:
      - "npm install"
      - "npm run build"

ci_test:
  tests:
    -
      customized_builder_image:
        registry: artifactory
        url: artifactory.dev.adskengineer.net/docker-local-v2/dynamo/dynamolibrariejs:dotnetcore2
      scripts:
        - "npm run test"
        - "npm run utiltest"
  test_report_dir: TestResults
  test_report_pattern:
    format: "junit"
    pattern: "*.xml"

deployment:
  -
    type: customized
    customized_builder_image:
      registry: artifactory
      url: artifactory.dev.adskengineer.net/docker-local-v2/dynamo/dynamolibrariejs:dotnetcore2
    scripts:
      - "dotnet pack -c Release -o nuget --version-suffix \"beta$BUILD_NUMBER\""
      - "dotnet nuget push \"$(find nuget -type f -name *.nupkg)\" -s https://api.nuget.org/v3/index.json -k $API_KEY"
soc2:
  run_on_any_branch : true
  white_source:    
    skip: false
    fail_on_audit_failure: true
    team: Dynamo
    project_name: "librarie.js"
    hidden_email_list: dynamo_ws_access
    third_party_lib_paths:
      - "node_modules"