version: 0.1.1
env:
  - SLACK_QUANTUM_BUILD_CHANNEL : "#dynamo-jenkinsbuild"
  - SLACK_QUANTUM_BUILD_CREDENTIAL_ID : "slack-notify-token"
  - MAIL_QUANTUM_BUILD_RECIPIENT : "dynamo.dev@autodesk.com"
  - ARTIFACTORY_BOBCAT_DOCKER_REGISTRY : "artifactory.dev.adskengineer.net"
  - NUGET_API_ID : "dynamovisualprogramming_nuget_api_key"
  - ARTIFACTORY_DOCKER_CREDENTIALS_ID : "common_service_account"
  - HARMONY_REPO : "DynamoDS/librarie.js"

check_changelog_updated_on_pr: false
pipeline_os: "Linux"
force_slack_notification : true
language: typescript

jenkins_creds:
  -
    type: secretText
    credentialsId: dynamovisualprogramming_nuget_api_key
    secretText: API_KEY

build:
  -
    customized_builder_image:
      registry: artifactory
      url: artifactory.dev.adskengineer.net/dynamo/dynamolibrariejs:dotnetcore3_node16_v2
    scripts:
      - "mv -f /home/ctr-user/.npmrc $WORKSPACE"
      - "npm ci"
      - "npm run build"

ci_test:
  tests:
    -
      customized_builder_image:
        registry: artifactory
        url: artifactory.dev.adskengineer.net/dynamo/dynamolibrariejs:dotnetcore3_node16_v2
      scripts:
        - "npm run test"
        - "npm run utiltest"
  test_report_dir: TestResults
  test_report_pattern:
    format: "junit"
    pattern: "*.xml"

deployment:
  -
    type: customized
    customized_builder_image:
      registry: artifactory
      url: artifactory.dev.adskengineer.net/dynamo/dynamolibrariejs:dotnetcore3_node16_v2
    scripts:
      - "dotnet pack -c Release -o nuget --version-suffix \"beta$BUILD_NUMBER\""
      - "dotnet nuget push \"$(find nuget -type f -name *.nupkg)\" -s https://api.nuget.org/v3/index.json -k $API_KEY"
      
soc2:
  run_on_any_branch : true
  harmony:
    product_name: Dynamo
    hidden_email_list: dynamo_ws_access
    repository: env.HARMONY_REPO
    timeout: 3000

schedule:
  cron_schedule: "once_a_week"

code_analysis:
  sonarqube:
    useCommonSonar: true
    project_name: librarie.js
    organization: Dynamo
    src: "."
    exclusions:
      - __tests__/**/*
      - node_modules/**/*
      - dist/**/*
