version: 0.1.1
env:
  - SLACK_QUANTUM_BUILD_CHANNEL : "#dynamo-jenkinsbuild"
  - SLACK_QUANTUM_BUILD_CREDENTIAL_ID : "slack-notify-token"
  - MAIL_QUANTUM_BUILD_RECIPIENT : "dynamo.plaid.dev@autodesk.com"
  - TEST_REPORT_FORMAT : "junit"

check_changelog_updated_on_pr: false
pipeline_os: "Linux"
force_slack_notification : true
language: typescript
nodejs_version: "10"

build:
  customized_builder_image:
    registry: artifactory
    url: autodesk-docker.art-bobcat.autodesk.com/quantum/hardened-nodejs:latest
  before_scripts:
    - "npm install"
  scripts:
    - "npm run build"  

ci_test:
  customized_builder_image:
    registry: artifactory
    url: autodesk-docker.art-bobcat.autodesk.com/quantum/hardened-nodejs:latest
  scripts:
    - "npm run test"
    - "npm run utiltest"
  
  test_report_dir: TestResults